/*
** EPITECH PROJECT, 2024
** B-CPE-110-BDX-1-1-secured-maxime.goyheneche
** File description:
** hashtable_destroyer header
*/

#ifndef B_CPE_110_BDX_1_1_SECURED_MAXIME_GOYHENECHE_HASHTABLE_DESTROYER_H
    #define B_CPE_110_BDX_1_1_SECURED_MAXIME_GOYHENECHE_HASHTABLE_DESTROYER_H
    #include "hashtable.h"
#endif //B_CPE_110_BDX_1_1_SECURED_MAXIME_GOYHENECHE_HASHTABLE_DESTROYER_H
